### ISSUE TITLE
humanoid doesn't move at all

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [rohanpsingh/LearningHumanoidWalking#12]
I need to write a script specific for debug_stepper.py can be used with the jvrc_step environment.
Then, I tried to run the following command.

```
PYTHONPATH=.:$PYTHONPATH python3 scripts/debug_stepper.py --path ./log
```

Then, the following image was shown.

![image](https://user-images.githubusercontent.com/23301778/224859739-ad6bf04a-2f6b-4f73-9fe2-64326b3e4564.png)

But, it doesn't move at all.
What should I do to move the numanoid?

**Comment by rohanpsingh** [comment]
The simulation is probably paused. I guess you need to press [Space] key.
