### ISSUE TITLE
Many thanks to the author for his contribution to humanoid robots

### ISSUE THREAD

**Issue by zhangqingbo6** [rohanpsingh/LearningHumanoidWalking#16]
I have a problem. When I reproduce your code, the humanoid robot only moves up and down the stairs on one plane and does not go up or down the stairs.
![lv_0_20231116171722](https://github.com/rohanpsingh/LearningHumanoidWalking/assets/56789308/9df70ac5-8617-4861-b2b6-415dfc3b942b)

**Comment by rohanpsingh** [comment]
Hi, can you retry after downgrading mujoco version to 2.3.0? `$ pip install mujoco==2.3.0`

**Comment by zhangqingbo6** [comment]
1. My humanoid robot still falls down when going up stairs after training. The experiment of going down stairs still moves on the current plane.
![lv_0_20231116204119](https://github.com/rohanpsingh/LearningHumanoidWalking/assets/56789308/9db19d08-3e66-4c11-89c7-bfbc444234a7)
![lv_0_20231116204511](https://github.com/rohanpsingh/LearningHumanoidWalking/assets/56789308/83914984-2205-4f9d-85f2-59e2dad36c59)
3.  Why is it a different task every time "PYTHONPATH=.:$PYTHONPATH python scripts/debug_stepper.py --path <path_to_exp_dir>" is executed? How to choose the specified task? Thanks!

**Comment by Wenhaocui** [comment]
> 1. My humanoid robot still falls down when going up stairs after training. The experiment of going down stairs still moves on the current plane.
>    ![lv_0_20231116204119](https://user-images.githubusercontent.com/56789308/283453785-9db19d08-3e66-4c11-89c7-bfbc444234a7.gif)
>          
>            [
>              
>            
>                ![lv_0_20231116204119](https://user-images.githubusercontent.com/56789308/283453785-9db19d08-3e66-4c11-89c7-bfbc444234a7.gif)
>              ](https://user-images.githubusercontent.com/56789308/283453785-9db19d08-3e66-4c11-89c7-bfbc444234a7.gif)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://user-images.githubusercontent.com/56789308/283453785-9db19d08-3e66-4c11-89c7-bfbc444234a7.gif)
>            
>          
>    ![lv_0_20231116204511](https://user-images.githubusercontent.com/56789308/283453799-83914984-2205-4f9d-85f2-59e2dad36c59.gif)
>          
>            [
>              
>            
>                ![lv_0_20231116204511](https://user-images.githubusercontent.com/56789308/283453799-83914984-2205-4f9d-85f2-59e2dad36c59.gif)
>              ](https://user-images.githubusercontent.com/56789308/283453799-83914984-2205-4f9d-85f2-59e2dad36c59.gif)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://user-images.githubusercontent.com/56789308/283453799-83914984-2205-4f9d-85f2-59e2dad36c59.gif)
> 2. Why is it a different task every time "PYTHONPATH=.:$PYTHONPATH python scripts/debug_stepper.py --path <path_to_exp_dir>" is executed? How to choose the specified task? Thanks!
1. add pos="0 0 -100" in floor geom  in models/jvrc_mj_description/xml/scene.xml file. In my test, self._client.model.geom('floor').pos[:] can only be higher than default set in z axis (Don't know the reason).
2. In tasks/stepping_task.py, set self.mode = WalkModes.BACKWARD(or anyone else) in reset func

**Comment by rohanpsingh** [comment]
Sorry for the delay. Indeed, solution proposed by @Wenhaocui should work for climbing down the stairs. Another solution is [here](https://github.com/rohanpsingh/LearningHumanoidWalking/discussions/15#discussioncomment-7350643).

> My humanoid robot still falls down when going up stairs after training.

Are you training from scratch? Can you first please confirm that the pre-trained weights provided in this repository work fine?

**Comment by bottlele** [comment]
Hello, when executing the command python scripts/debug_stepper.py --path trained/jvrc_stepper/actor.pt, climbing stairs works normally, but when descending stairs, there's a fall at the last step. What could be the reason for this?

**Comment by rohanpsingh** [comment]
> Hello, when executing the command python scripts/debug_stepper.py --path trained/jvrc_stepper/actor.pt, climbing stairs works normally, but when descending stairs, there's a fall at the last step. What could be the reason for this?

Fixed in 7f28e0327293f9fbc87587c21d00b24c9ff7efbc.
