### ISSUE TITLE
Questions about the current feedback and the swing problem

### ISSUE THREAD

**Issue by Wenhaocui** [rohanpsingh/LearningHumanoidWalking#18]
Hi Sir，
    Thank you for sharing such valuable research. But I have two questions I would like to ask you.
    The first is that I don't know where the Current Feedback part of the paper is represented in the code. Could you help me to figure it out?
     The second question is the leg swing in the hips' yaw direction that you mentioned before. May I ask that did you update some reward functions to avoid this problem?

**Comment by rohanpsingh** [comment]
Hi, thanks for the comment.  
Sorry the current feedback part is not pushed yet, the reason being that the paper implements it for the HRP-5P robot while this repository uses the JVRC-1 robot. The code for achieving omnidirectional walking is on `topic/omnidirectional` (see https://github.com/rohanpsingh/LearningHumanoidWalking/compare/main...topic/omnidirectional-walk). I may add the code for simulating degraded torque-tracking in this repository at some point in the future, hopefully soon. In essence, the idea is to add some random noise proportional to the joint velocity to the applied torque at each timestep.  

Do you mean the outward sway motion of the swing leg? If you observe such behavior in simulation after training, I recommend you to tune the PD gains. If you observe this behavior appears on the real robot but not in simulation, using current feedback may help.

**Comment by Wenhaocui** [comment]
Thanks for your reply. I hope your future research will go well, sir.
