### ISSUE TITLE
Problem with steps. Going through the steps instead of climbing or descending

### ISSUE THREAD

**Issue by ParasVekariya** [rohanpsingh/LearningHumanoidWalking#32]
Hello,I was trying to run this project as a learning step towards Reinforcement learning, and during this I am facing certain issues mainly in the part concerning the climbing of the Humanoid . I have used the pre-trained model as well as trained a new model so that I can see how it behaves for different levels of training, and in both cases I observed that the robot is unable to climb or descend through the steps. It is simply going through the steps. I have tried to go through the issues section where I found similar issues and have taken the necessary steps, but was unable to get the results. 

I tried downgrading the mujoco version to 2.2.0 but, dm-control is automatically updating it to the latest version. Also tried to downgrade the dm-control but was unable to solve the issue, because it goes into a hierarchy of libraries and dependencies to be downgraded

- I also tried to change through XML files but was unable to solve it.
- I think maybe the issue is with the ground plane because while descending, The stairs are below the ground plane which is only visible when you move the camera.

It would be a great help if someone could guide me here.

https://github.com/rohanpsingh/LearningHumanoidWalking/assets/81183082/d8c2027c-f131-4e48-9355-87e5fb3fcec6

**Comment by rohanpsingh** [comment]
Hi, I pushed some changes in 02ec37361ab4986891c02b9992aa670ba5844204. Could you please pull and retry?

**Comment by ParasVekariya** [comment]
Thank you so much for helping on such short notice. Now it is working properly and also it not falling of the last step anymore. Here is the video for the same. 


https://github.com/rohanpsingh/LearningHumanoidWalking/assets/81183082/f7b02fbb-9cc4-4fc3-bcf2-db11cc3cf7cf

I just have 2 more doubts 

- First is can we monitor the speed of the robot? If yes can you please guide me.
- Secondly, the environment of climbing, descending, walking on curves appears to be generated randomly. Can I always fix it to climbing or descending only? If Yes can you please help here as well.

Thanks in advance.

**Comment by rohanpsingh** [comment]
- Depends on what you mean by "speed" of robot. Linear velocity in x-direction of root body can be accessed by `data.qvel[0]`. 
- Sorry, you need to manually edit `stepping_task.py` to achieve this. Basically, replace [this](https://github.com/rohanpsingh/LearningHumanoidWalking/blob/dbeed7ac0a66a1c99fa57623ffa90c5d902d0c7b/tasks/stepping_task.py#L269-L271) with whatever mode you would like to choose, say `self.mode = WalkModes.FORWARD`
